# -*- coding: utf-8 -*-
"""giornazi_shada_hw1pr2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeGY14OeoBIxc7KX1orcd6d28r6V7P8-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time


###########################################
#           Main Driver Function
###########################################

if __name__ == '__main__':

    # =====================================================
    # PART C: Plot data and the optimal linear fit
    # =====================================================

    # Load the four original data points
    X = np.array([0, 2, 3, 4])
    y = np.array([1, 3, 6, 8])

    # Plot the original data points
    plt.style.use('ggplot')
    plt.plot(X, y, 'ro')

    # Optimal coefficients from part (a)
    m_opt = 62 / 35
    b_opt = 18 / 35

    # Generate 100 evenly spaced x-coordinates
    X_space = np.linspace(0, 4, 100)

    # Calculate 100 y-coordinates
    y_space = m_opt * X_space + b_opt

    # Reshape both arrays into column vectors
    X_space = X_space.reshape(-1, 1)
    y_space = y_space.reshape(-1, 1)

    # Plot the optimal linear fit
    plt.plot(X_space, y_space)

    # Save the first figure
    plt.savefig('hw1pr2c.png', format='png')
    plt.close()


    # =====================================================
    # PART D: Optimal linear fit with random data points
    # =====================================================

    # Gaussian noise parameters
    mu, sigma, sampleSize = 0, 1, 100

    # Set random seed for reproducibility
    np.random.seed(42)

    # Generate white Gaussian noise
    noise = np.random.normal(mu, sigma, sampleSize)

    # Reshape noise into a column vector
    noise = noise.reshape(-1, 1)

    # Generate 100 noisy observations
    y_space_rand = X_space * m_opt + b_opt + noise

    # =====================================================
    # Calculate new optimal regression coefficients
    # =====================================================

    # Create a column of ones
    x_col1 = np.ones_like(X_space)

    # Construct the design matrix
    X_space_stacked = np.hstack((x_col1, X_space))

    # Solve the normal equations
    W_opt = np.linalg.solve(
        X_space_stacked.T @ X_space_stacked,
        X_space_stacked.T @ y_space_rand
    )

    # Extract the new intercept and slope
    b_rand_opt, m_rand_opt = W_opt.item(0), W_opt.item(1)

    # Generate predicted y-values using the new coefficients
    y_pred_rand = m_rand_opt * X_space + b_rand_opt

    # Ensure the predictions are a column vector
    y_pred_rand = y_pred_rand.reshape(-1, 1)

    # =====================================================
    # Plot original data, noisy data, and regression lines
    # =====================================================

    # Plot original data points and original regression line
    plt.plot(X, y, 'ro')
    orig_plot, = plt.plot(X_space, y_space, 'r')

    # Plot noisy observations and new regression line
    plt.plot(X_space, y_space_rand, 'bo')
    rand_plot, = plt.plot(X_space, y_pred_rand, 'b')

    # Add legend
    plt.legend(
        (orig_plot, rand_plot),
        ('original fit', 'fit with noise'),
        loc='best'
    )

    # Save the second figure
    plt.savefig('hw1pr2d.png', format='png')
    plt.close()

    # =====================================================
    # Print results for verification
    # =====================================================

    print("Original slope:", m_opt)
    print("Original intercept:", b_opt)

    print("New slope:", m_rand_opt)
    print("New intercept:", b_rand_opt)

    print("X_space shape:", X_space.shape)
    print("Design matrix shape:", X_space_stacked.shape)
    print("Noisy observations shape:", y_space_rand.shape)

    print("Both plots saved successfully.")

