# -*- coding: utf-8 -*-
"""giornazi_shada_hw2pr3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xTUhHEZGRQ_MavgC5cK_9IeL5Bp2x27
"""

"""
Start file for hw2pr3 of Big Data Summer 2017

The file is seperated into two parts:
    1) the helper functions
    2) the main driver.

The helper functions are all functions necessary to finish the problem.
The main driver will use the helper functions you finished to report and print
out the results you need for the problem.

Before attemping the helper functions, please familiarize with pandas and numpy
libraries. Tutorials can be found online.

First, fill in the code of step 0 in the main driver to load the data, then
please COMMENT OUT any steps in main driver before you finish the corresponding
functions for that step. Otherwise, you won't be able to run the program
because of errors.

After finishing the helper functions for each step, you can uncomment
the code in main driver to check the result.

Note:
1. When filling out the functions below, remember to
    1) Let m be the number of samples
    2) Let n be the number of features

2. Please read the instructions and hints carefully, and use the name of the
variables we provided, otherwise, the function may not work.

3. Remember to comment out the TODO comment after you finish each part.
"""


#########################################
#            Helper Functions           #
#########################################

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time


#########################
#        Part C         #
#########################

def linreg(X, y, reg=0.0):
    """This function takes in three arguments:
        1) X, the data matrix with dimension m x (n + 1)
        2) y, the label of the data with dimension m x 1
        3) reg, the parameter for regularization

    This function calculates and returns the optimal weight matrix, W_opt.

    HINT: Find the numerical solution for part C
        1) use np.eye to create identity matrix
        2) use np.linalg.solve to solve for W_opt
    """

    # create identity matrix for regularization
    n = X.shape[1]
    R = np.eye(n)

    # do not regularize the bias
    R[0, 0] = 0

    # solve (X^T X + lambda R)W = X^T y
    W_opt = np.linalg.solve(
        X.T * X + reg * R,
        X.T * y
    )

    return W_opt


def predict(W, X):
    """This function takes in two arguments:
        1) W, a weight matrix with bias
        2) X, the data with dimension m x (n + 1)

    This function calculates and returns the predicted label, y_pred.

    NOTE: You don't need to change this function.
    """

    return X * W


def find_RMSE(W, X, y):
    """This function takes in three arguments:
        1) W, a weight matrix with bias
        2) X, the data with dimension m x (n + 1)
        3) y, the label of the data with dimension m x 1

    This function calculates and returns the root mean-squared error, RMSE.
    """

    # calculate predictions
    y_pred = predict(W, X)

    # calculate RMSE
    RMSE = np.sqrt(np.mean(np.square(y_pred - y)))

    return RMSE


def RMSE_vs_lambda(X_train, y_train, X_val, y_val):
    """This function takes in four arguments:
        1) X_train, the training data with dimension m x (n + 1)
        2) y_train, the label of training data with dimension m x 1
        3) X_val, the validation data with dimension m x (n + 1)
        4) y_val, the label of validation data with dimension m x 1

    This function generates a plot of RMSE vs lambda and returns the
    regularization parameter that minimizes RMSE, reg_opt.
    """

    RMSE_list = []
    reg_list = []
    W_list = []

    # generate at least 150 random lambda values between 0 and 150
    reg_list = np.random.uniform(0.0, 150.0, 150)

    # sort them so the plot is readable
    reg_list = np.sort(reg_list)

    # train and evaluate for each lambda
    for reg in reg_list:
        W_opt = linreg(X_train, y_train, reg)
        W_list.append(W_opt)

        RMSE = find_RMSE(W_opt, X_val, y_val)
        RMSE_list.append(RMSE)

    # set up plot style
    plt.style.use('ggplot')

    # plot RMSE vs lambda
    RMSE_vs_lambda_plot, = plt.plot(reg_list, RMSE_list)
    plt.setp(RMSE_vs_lambda_plot, color='red')
    plt.title('RMSE vs lambda')
    plt.xlabel('lambda')
    plt.ylabel('RMSE')
    plt.savefig('RMSE_vs_lambda.png', format='png')
    plt.close()
    print('==> Plotting completed.')

    # find lambda with minimum validation RMSE
    min_index = np.argmin(RMSE_list)
    reg_opt = reg_list[min_index]

    return reg_opt


def norm_vs_lambda(X_train, y_train, X_val, y_val):
    """This function takes in four arguments:
        1) X_train, the training data with dimension m x (n + 1)
        2) y_train, the label of training data with dimension m x 1
        3) X_val, the validation data with dimension m x (n + 1)
        4) y_val, the label of validation data with dimension m x 1

    This function generates a plot of norm of the weights vs lambda.
    """

    reg_list = []
    W_list = []
    norm_list = []

    # generate lambda values
    reg_list = np.random.uniform(0.0, 150.0, 150)
    reg_list = np.sort(reg_list)

    # calculate optimal weights and their norms
    for reg in reg_list:
        W_opt = linreg(X_train, y_train, reg)
        W_list.append(W_opt)

        # exclude bias from weight norm
        norm = np.linalg.norm(W_opt[1:])
        norm_list.append(norm)

    # set up plot style
    plt.style.use('ggplot')

    # plot norm vs lambda
    norm_vs_lambda_plot, = plt.plot(reg_list, norm_list)
    plt.setp(norm_vs_lambda_plot, color='blue')
    plt.title('norm vs lambda')
    plt.xlabel('lambda')
    plt.ylabel('norm')
    plt.savefig('norm_vs_lambda.png', format='png')
    plt.close()
    print('==> Plotting completed.')


#########################
#        Part D         #
#########################

def linreg_no_bias(X, y, reg=0.0):
    """This function takes in three arguments:
        1) X, the data matrix
        2) y, the label of the data with dimension m x 1
        3) reg, the parameter for regularization

    This function calculates and returns the optimal weight matrix, W_opt
    and bias, b_opt separately.
    """

    t_start = time.time()

    # number of features
    n = X.shape[1]

    # calculate feature means and target mean
    X_mean = np.mean(X, axis=0)
    y_mean = np.mean(y, axis=0)

    # center X and y
    X_centered = X - X_mean
    y_centered = y - y_mean

    # regularization matrix
    I = np.eye(n)

    # solve for optimal weights
    W_opt = np.linalg.solve(
        X_centered.T * X_centered + reg * I,
        X_centered.T * y_centered
    )

    # recover optimal bias
    b_opt = y_mean - X_mean * W_opt

    # benchmark report
    t_end = time.time()
    print('--Time elapsed for training: {t:4.2f} seconds'.format(
        t=t_end - t_start
    ))

    return b_opt, W_opt


#########################
#        Part E         #
#########################

def grad_descent(X_train, y_train, X_val, y_val, reg=0.0,
                 lr_W=2.5e-12, lr_b=0.2, max_iter=150,
                 eps=1e-6, print_freq=25):
    """This function takes in ten arguments:
        1) X_train, the training data
        2) y_train, the label of training data
        3) X_val, the validation data
        4) y_val, the label of validation data
        5) reg, the parameter for regularization
        6) lr_W, the learning rate for weights
        7) lr_b, the learning rate for bias
        8) max_iter, the maximum number of iterations
        9) eps, the threshold of the norm for the gradients
        10) print_freq, the frequency of printing the report

    This function returns W, the optimal weight, and b, the bias by
    gradient descent.
    """

    m_train, n = X_train.shape
    m_val = X_val.shape[0]

    # initialize weights and bias
    W = np.matrix(np.zeros((n, 1)))
    b = 0.0

    # initialize gradients to nonzero values so the loop starts
    W_grad = np.matrix(np.ones((n, 1)))
    b_grad = 1.0

    print('==> Running gradient descent...')

    obj_train = []
    obj_val = []
    iter_num = 0

    t_start = time.time()

    # start iteration for gradient descent
    while np.linalg.norm(W_grad) > eps and \
            np.linalg.norm(b_grad) > eps and \
            iter_num < max_iter:

        # calculate predictions
        y_train_pred = X_train * W + b
        y_val_pred = X_val * W + b

        # calculate RMSE
        train_rmse = np.sqrt(
            np.mean(
                np.square(y_train_pred - y_train)
            )
        )

        val_rmse = np.sqrt(
            np.mean(
                np.square(y_val_pred - y_val)
            )
        )

        obj_train.append(train_rmse)
        obj_val.append(val_rmse)

        # calculate residual
        residual = X_train * W + b - y_train

        # calculate gradients
        W_grad = (
            (2.0 / m_train) * X_train.T * residual
            + 2.0 * reg * W
        )

        b_grad = (
            (2.0 / m_train) * np.sum(residual)
        )

        # gradient descent updates
        W = W - lr_W * W_grad
        b = b - lr_b * b_grad

        # print statements for debugging
        if (iter_num + 1) % print_freq == 0:
            print(
                '-- Iteration{} - training rmse {: 4.4f} '
                '- gradient norm {: 4.4E}'.format(
                    iter_num + 1,
                    train_rmse,
                    np.linalg.norm(W_grad)
                )
            )

        # goes to next iteration
        iter_num += 1

    # benchmark report
    t_end = time.time()
    print('--Time elapsed for training: {t:4.2f} seconds'.format(
        t=t_end - t_start
    ))

    # set up plot style
    plt.style.use('ggplot')

    # generate convergence plot
    train_rmse_plot, = plt.plot(range(iter_num), obj_train)
    plt.setp(train_rmse_plot, color='red')

    val_rmse_plot, = plt.plot(range(iter_num), obj_val)
    plt.setp(val_rmse_plot, color='green')

    plt.legend(
        (train_rmse_plot, val_rmse_plot),
        ('Training RMSE', 'Validation RMSE'),
        loc='best'
    )

    plt.title('RMSE vs iteration')
    plt.xlabel('iteration')
    plt.ylabel('RMSE')
    plt.savefig('convergence.png', format='png')
    plt.close()

    print('==> Plotting completed.')

    return b, W


###########################################
#           Main Driver Function          #
###########################################

# You should comment out the sections that
# you have not completed yet

if __name__ == '__main__':

    # =============STEP 0: LOADING DATA=================
    print('==> Loading data...')

    # read data
    df = pd.read_csv(
        'https://math189sp19.github.io/data/online_news_popularity.csv',
        sep=', ',
        engine='python'
    )

    # split the data frame by type: training, validation, and test
    train_pct = 2.0 / 3
    val_pct = 5.0 / 6

    df['type'] = ''
    df.loc[:int(train_pct * len(df)), 'type'] = 'train'
    df.loc[int(train_pct * len(df)):int(val_pct * len(df)), 'type'] = 'val'
    df.loc[int(val_pct * len(df)):, 'type'] = 'test'

    # extracting columns into training, validation, and test data
    X_train = np.array(
        df[df.type == 'train'][[
            col for col in df.columns
            if col not in ['url', 'shares', 'type']
        ]]
    )

    y_train = np.array(
        np.log(df[df.type == 'train'].shares)
    ).reshape((-1, 1))

    X_val = np.array(
        df[df.type == 'val'][[
            col for col in df.columns
            if col not in ['url', 'shares', 'type']
        ]]
    )

    y_val = np.array(
        np.log(df[df.type == 'val'].shares)
    ).reshape((-1, 1))

    X_test = np.array(
        df[df.type == 'test'][[
            col for col in df.columns
            if col not in ['url', 'shares', 'type']
        ]]
    )

    y_test = np.array(
        np.log(df[df.type == 'test'].shares)
    ).reshape((-1, 1))

    # stack a column of ones to the feature data
    X_train = np.hstack(
        (np.ones((X_train.shape[0], 1)), X_train)
    )

    X_val = np.hstack(
        (np.ones((X_val.shape[0], 1)), X_val)
    )

    X_test = np.hstack(
        (np.ones((X_test.shape[0], 1)), X_test)
    )

    # convert data to matrix
    X_train = np.matrix(X_train)
    y_train = np.matrix(y_train)
    X_val = np.matrix(X_val)
    y_val = np.matrix(y_val)
    X_test = np.matrix(X_test)
    y_test = np.matrix(y_test)

    # PART C
    # =============STEP 1: RMSE vs lambda=================
    print('==> Step 1: RMSE vs lambda...')

    # find the optimal regularization parameter
    reg_opt = RMSE_vs_lambda(
        X_train,
        y_train,
        X_val,
        y_val
    )

    print(
        '==> The optimal regularization parameter is '
        '{reg: 4.4f}.'.format(reg=reg_opt)
    )

    # find the optimal weights and bias for future use in step 3
    W_with_b_1 = linreg(X_train, y_train, reg=reg_opt)
    b_opt_1 = W_with_b_1[0]
    W_opt_1 = W_with_b_1[1:]

    # report the RMSE with the found optimal weights on validation set
    val_RMSE = find_RMSE(
        W_with_b_1,
        X_val,
        y_val
    )

    print(
        '==> The RMSE on the validation set with the optimal '
        'regularization parameter is {RMSE: 4.4f}.'.format(
            RMSE=val_RMSE
        )
    )

    # report the RMSE with the found optimal weights on test set
    test_RMSE = find_RMSE(
        W_with_b_1,
        X_test,
        y_test
    )

    print(
        '==> The RMSE on the test set with the optimal '
        'regularization parameter is {RMSE: 4.4f}.'.format(
            RMSE=test_RMSE
        )
    )

    # =============STEP 2: Norm vs lambda=================
    print('\n==> Step 2: Norm vs lambda...')

    norm_vs_lambda(
        X_train,
        y_train,
        X_val,
        y_val
    )

    # PART D
    # =============STEP 3: Linear regression without bias=================

    # from here on, we will strip the columns of ones for all data
    X_train = X_train[:, 1:]
    X_val = X_val[:, 1:]
    X_test = X_test[:, 1:]

    # compare the result with the one from step 1
    # the difference in norm should be a small scalar (i.e. 1e-10)
    print('\n==> Step 3: Linear regression without bias...')

    b_opt_2, W_opt_2 = linreg_no_bias(
        X_train,
        y_train,
        reg=reg_opt
    )

    # difference in bias
    diff_bias = np.linalg.norm(b_opt_2 - b_opt_1)

    print(
        '==> Difference in bias is '
        '{diff: 4.4E}'.format(diff=diff_bias)
    )

    # difference in weights
    diff_W = np.linalg.norm(W_opt_2 - W_opt_1)

    print(
        '==> Difference in weights is '
        '{diff: 4.4E}'.format(diff=diff_W)
    )

    # PART E
    # =============STEP 4: Gradient descent=================
    print('\n==> Step 4: Gradient descent')

    b_gd, W_gd = grad_descent(
        X_train,
        y_train,
        X_val,
        y_val,
        reg=reg_opt
    )

    # compare the result from the one from step 1

    # difference in bias
    diff_bias = np.linalg.norm(b_gd - b_opt_1)

    print(
        '==> Difference in bias is '
        '{diff: 4.4E}'.format(diff=diff_bias)
    )

    # difference in weights
    diff_W = np.linalg.norm(W_gd - W_opt_1)

    print(
        '==> Difference in weights is '
        '{diff: 4.4E}'.format(diff=diff_W)
    )