# -*- coding: utf-8 -*-
"""giornazi, shada HW4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxCNhyW1vtBo4ckoskIiLunLcNdp5uVs
"""

# Commented out IPython magic to ensure Python compatibility.
# # i had some issues with accessing the data so this is me making it accessable to my code
# %%writefile p2_data.py
# 
# """
# Used to load and process the MNIST data for Problem 2.
# """
# 
# print("==>Loading data...")
# 
# import numpy as np
# import pandas as pd
# from sklearn.datasets import fetch_openml
# 
# 
# # Load MNIST
# mnist = fetch_openml(
#     'mnist_784',
#     version=1,
#     as_frame=False
# )
# 
# # Get image data and labels
# X = mnist.data.astype(float)
# y = mnist.target.astype(int).reshape(-1, 1)
# 
# 
# # Use standard MNIST training/testing split
# X_train = X[:60000]
# y_train = y[:60000]
# 
# X_test = X[60000:]
# y_test = y[60000:]
# 
# 
# # Create column names expected by the homework
# name_list = ['label']
# 
# for i in range(784):
#     name_list.append('pix_' + str(i))
# 
# 
# # Create data frames in the same format as the original starter
# df_train = pd.DataFrame(
#     np.hstack((y_train, X_train)),
#     columns=name_list
# )
# 
# df_test = pd.DataFrame(
#     np.hstack((y_test, X_test)),
#     columns=name_list
# )
# 
# 
# # Make labels integers
# df_train['label'] = df_train['label'].astype(int)
# df_test['label'] = df_test['label'].astype(int)
# 
# 
# # Scale data for Part B
# X_train = X_train / 256.
# X_test = X_test / 256.
# 
# 
# print("==>Data loaded successfully.")
# print("Training data shape:", X_train.shape)
# print("Testing data shape:", X_test.shape)

!head -20 p2_data.py

import os
import sys

print("Current working directory:")
print(os.getcwd())

print("\nFiles in current directory:")
print(os.listdir())

print("\np2_data locations found:")
!find /content -name "p2_data.py" -print

print("\nRemoving cached p2_data module...")
if 'p2_data' in sys.modules:
    del sys.modules['p2_data']

print("Done.")

with open('/content/p2_data.py', 'r') as f:
    contents = f.read()

print("Old URL still exists:", "pjreddie.com" in contents)

import p2_data

print("\nLoaded from:")
print(p2_data.__file__)

print("\nData shapes:")
print("X_train:", p2_data.X_train.shape)
print("y_train:", p2_data.y_train.shape)
print("X_test:", p2_data.X_test.shape)
print("y_test:", p2_data.y_test.shape)

"""
Start file for hw1pr2 of Big Data Summer 2017

This file is used to load and process data for problem 2, and is imported

Note:
1. Please DO NOT change anything in this file.
2. Although these codes are given, please read carefully through the file, and
   make sure you understand how these codes work.
"""
import pandas as pd
import numpy as np


print('==>Loading data...')

# create the headers for data frame since original data dodes not have headers
name_list = ['pix_{}'.format(i + 1) for i in range(784)]
name_list = ['label'] + name_list

# read the training data
df_train = pd.read_csv('http://pjreddie.com/media/files/mnist_train.csv', \
	sep=',', engine='python', names = name_list)

# read the test data
df_test = pd.read_csv('http://pjreddie.com/media/files/mnist_test.csv', \
	sep=',', engine='python', names = name_list)

print('==>Data loaded succesfully.')


# Process training data, so that X (pixels) and y (labels) are seperated
X_train = np.array(df_train[:][[col for col in df_train.columns \
	if col != 'label']]) / 256.

y_train = np.array(df_train[:][['label']])


# Process test data, so that X (pixels) and y (labels) are seperated
X_test = np.array(df_test[:][[col for col in df_test.columns \
	if col != 'label']]) / 256.

y_test = np.array(df_test[:][['label']])

!wget -O mnist_train.csv https://pjreddie.com/media/files/mnist_train.csv
!wget -O mnist_test.csv https://pjreddie.com/media/files/mnist_test.csv

!ls -lh mnist_train.csv mnist_test.csv

"""
Start file for hw4pr2 part(a) of Big Data Summer 2017

The file is seperated into two parts:
    1) the helper functions
    2) the main driver.

The helper functions are all functions necessary to finish the problem.
The main driver will use the helper functions you finished to report and print
out the results you need for the problem.

First, please COMMENT OUT any steps other than step 0 in main driver before
you finish the corresponding functions for that step. Otherwise, you won't be
able to run the program because of errors.

After finishing the helper functions for each step, you can uncomment
the code in main driver to check the result.

Note:
1. Please read the instructions and hints carefully, and use the name of the
variables we provided, otherwise, the function may not work.

2. Remember to comment out the TODO comment after you finish each part.
"""


#########################################
#            Helper Functions           #
#########################################

import p2_data as data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time


#########################
#       Step 1a         #
#########################

def sigmoid(x):
    """ This function takes in one argument:
            1) x, a numpy array

        This function applies the sigmoid / logistic function on each entry of
        the input array returns the new array.

        NOTE: You don't need to change this function.
    """
    return 1. / (1. + np.exp(-x))


def grad_logreg(X, y, W, reg=0.0):
    """ This function takes in four arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) y, the label of the data with dimension m x 1
            3) W, a weight matrix with bias
            4) reg, the parameter for regularization

        This function calculates and returns the gradient of W for logistic
        regression.

        HINT:
            1) Recall the log likelihood function for logistic regression and
               get the gradient with respect to the weight matrix, W
            2) Remember to apply the l2 regularization
            3) You will need to use the sigmoid function above

        NOTE: Please use the variable given for the gradient, grad.
    """

    # Find the gradient of logistic regression with respect to W
    mu = sigmoid(X @ W)

    grad = X.T @ (mu - y) + 2 * reg * W

    return grad


def NLL(X, y, W, reg=0.0):
    """ This function takes in four arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) y, the label of the data with dimension m x 1
            3) W, a weight matrix with bias
            4) reg, the parameter for regularization

        This function calculates and returns negative log likelihood of the
        logistic regression with l2 regularization

        HINT:
            1) Recall the negative log likelihood function for logistic regression.
            2) Use a.sum() to find the summation of all entries in a numpy
               array a
            3) Use np.linalg.norm to find the norm of a given vector
            4) Use np.log to caculate the log of each entry of the input array

        NOTE: please use the variable given for the final returned result, nll.
    """

    # Find the negative log likelihood of logistic regression
    mu = sigmoid(X @ W)

    # Prevent taking log(0)
    mu = np.clip(mu, 1e-12, 1 - 1e-12)

    nll = -(y * np.log(mu) + (1 - y) * np.log(1 - mu)).sum()
    nll += reg * (np.linalg.norm(W) ** 2)

    return nll


def grad_descent(X, y, reg=0.0, lr=1e-4, eps=1e-6,
                 max_iter=500, print_freq=20):
    """ This function takes in seven arguments:
            1) X, the data with dimension m x (n + 1)
            2) y, the label of data with dimension m x 1
            3) reg, the parameter for regularization
            4) lr, the learning rate
            5) eps, the threshold of the norm for the gradients
            6) max_iter, the maximum number of iterations
            7) print_freq, the frequency of printing the report

        This function returns W, the optimal weight by gradient descent,
        and nll_list, the corresponding learning objectives.
    """

    # get the shape of the data, and initiate nll list
    m, n = X.shape
    nll_list = []

    # initialize the weight and its gradient
    W = np.zeros((n, 1))
    W_grad = np.ones_like(W)

    print('\n==> Running gradient descent...')

    # Start iteration for gradient descent
    iter_num = 0
    t_start = time.time()

    # Run gradient descent algorithms
    while iter_num < max_iter and np.linalg.norm(W_grad) > eps:

        # Calculate the negative log likelihood
        nll = NLL(X, y, W, reg)

        # Append negative log likelihood to the list
        nll_list.append(nll)

        # Calculate the gradient for W
        W_grad = grad_logreg(X, y, W, reg)

        # Update W
        W = W - lr * W_grad

        # Print statements for debugging
        if (iter_num + 1) % print_freq == 0:
            print('-- Iteration {} - negative log likelihood {: 4.4f}'.format(
                iter_num + 1, nll))

        # Goes to the next iteration
        iter_num += 1

    # benchmark
    t_end = time.time()
    print('-- Time elapsed for running gradient descent: '
          '{t:2.2f} seconds'.format(t=t_end - t_start))

    return W, nll_list


#########################
#       Step 1b         #
#########################

def newton_step(X, y, W, reg=0.0):
    """ This function takes in four arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) y, the label of the data with dimension m x 1
            3) W, a weight matrix with bias
            4) reg, the parameter for regularization

        This function calculates and returns the change of W according to
        the Newton's method

        HINT: get the result following the steps below
            1) Calculate the gradient of log likelihood, grad, with respect to W
            2) Use np.diag to create a diagonal matrix, with mu*(1-mu) being the
               entries on the diagonal
            3) Calculate the Hessian matrix, H, of logistic regression following
               the equation (you will need to use the diagonal matrix created)
            4) Using np.linalg.solve to solve for d in the equation Hd = -grad

        NOTE: Please use the variable given for final returned result, d.
    """

    # Find the change of the weight according to Newton's method
    mu = sigmoid(X @ W)

    # Calculate gradient
    grad = grad_logreg(X, y, W, reg)

    # Create diagonal matrix
    S = np.diag((mu * (1 - mu)).flatten())

    # Calculate Hessian
    H = X.T @ S @ X + 2 * reg * np.eye(W.shape[0])

    # Solve Hd = -grad
    d = np.linalg.solve(H, -grad)

    return d


def newton_method(X, y, reg=0.0, eps=1e-6,
                  max_iter=20, print_freq=5):
    """ This function takes in six arguments:
            1) X, the data with dimension m x (n + 1)
            2) y, the label of data with dimension m x 1
            3) reg, the parameter for regularization
            4) eps, the threshold of the norm for the gradients
            5) max_iter, the maximum number of iterations
            6) print_freq, the frequency of printing the report

        This function returns W, the optimal weight by Newton's Method,
        and nll_list, the corresponding learning objectives.
    """

    # get the shape of the data, and initiate nll list
    m, n = X.shape
    nll_list = []

    # initialize the weight and its gradient
    W = np.zeros((n, 1))
    step = np.ones_like(W)

    print("==> Running Newton's method...")

    # Start iteration
    iter_num = 0
    t_start = time.time()

    # Run Newton's method
    while iter_num < max_iter and np.linalg.norm(step) > eps:

        # Calculate negative log likelihood
        nll = NLL(X, y, W, reg)

        # Append negative log likelihood
        nll_list.append(nll)

        # Calculate Newton step
        step = newton_step(X, y, W, reg)

        # Update W
        W = W + step

        # Print statements for debugging
        if (iter_num + 1) % print_freq == 0:
            print('-- Iteration {} - negative log likelihood {: 4.4f}'.format(
                iter_num + 1, nll))

        # Goes to the next iteration
        iter_num += 1

    # benchmark
    t_end = time.time()
    print("-- Time elapsed for running Newton's method: "
          "{t:2.2f} seconds".format(t=t_end - t_start))

    return W, nll_list


#########################
#        Step 3         #
#########################

def predict(X, W):
    """ This function takes in two arguments:
            1) W, a weight matrix with bias
            2) X, the data with dimension m x (n + 1)

        This function calculates and returns the predicted label.

        NOTE: You don't need to change this function.
    """

    mu = sigmoid(X @ W)

    return (mu >= 0.5).astype(int)


def get_description(X, y, W):
    """ This function takes in three arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) y, the label of the data with dimension m x 1.
            3) W, the weight matrix with bias and dimension (n + 1) x 1

        This function calculates and returns the accuracy, precision,
        recall and F-1 score of the prediction.

        HINT:
            1) Get the predict labels using predict defined above
            2) Accuracy = probability of correct prediction
            3) Precision = probability of true label being 1 given that the
               predicted label is 1
            4) Recall = probability of predicted label being 1 given that the
               true label is 1
            5) F-1 = 2*p*r / (p + r), where p = precision and r = recall

        NOTE: Please use the variable given for final returned results.
    """

    # Find predicted labels
    y_pred = predict(X, W)

    # Calculate accuracy
    accuracy = (y_pred == y).sum() / len(y)

    # Calculate true positives, false positives, and false negatives
    true_positive = ((y_pred == 1) & (y == 1)).sum()
    false_positive = ((y_pred == 1) & (y == 0)).sum()
    false_negative = ((y_pred == 0) & (y == 1)).sum()

    # Calculate precision
    precision = true_positive / (true_positive + false_positive)

    # Calculate recall
    recall = true_positive / (true_positive + false_negative)

    # Calculate F-1 score
    f1 = 2 * precision * recall / (precision + recall)

    return accuracy, precision, recall, f1


def plot_description(X_train, y_train, X_test, y_test):
    """ This function takes in four arguments:
            1) X_train, the training data with dimension m x (n + 1)
            2) y_train, the label of training data with dimension m x 1
            3) X_test, the testing data with dimension m x (n + 1)
            4) y_test, the label of testing data with dimension m x 1

        This function plots the accuracy/precision/recall/F-1 score versus
        lambda and returns the lambda that maximizes accuracy.
    """

    # At least 10 lambda values, including lambda = 0
    reg_list = [0.0, 1e-6, 1e-5, 1e-4, 1e-3,
                1e-2, 0.1, 1.0, 10.0, 30.0]

    a_list = []
    p_list = []
    r_list = []
    f1_list = []

    # Find the list of accuracy, precision, recall, and f-1 score
    # for different values of lambda
    for reg in reg_list:

        # Run gradient descent
        W_opt, nll_list = grad_descent(
            X_train, y_train, reg=reg
        )

        # Get testing descriptions
        accuracy, precision, recall, f1 = get_description(
            X_test, y_test, W_opt
        )

        # Append results
        a_list.append(accuracy)
        p_list.append(precision)
        r_list.append(recall)
        f1_list.append(f1)

        print('-- Lambda = {:2.6f}, Accuracy = {:2.4f}'.format(
            reg, accuracy))

    # Generate plots
    # plot accuracy versus lambda
    a_vs_lambda_plot, = plt.plot(reg_list, a_list)
    plt.setp(a_vs_lambda_plot, color='red')

    # plot precision versus lambda
    p_vs_lambda_plot, = plt.plot(reg_list, p_list)
    plt.setp(p_vs_lambda_plot, color='green')

    # plot recall versus lambda
    r_vs_lambda_plot, = plt.plot(reg_list, r_list)
    plt.setp(r_vs_lambda_plot, color='blue')

    # plot f1 score versus lambda
    f1_vs_lambda_plot, = plt.plot(reg_list, f1_list)
    plt.setp(f1_vs_lambda_plot, color='yellow')

    # Set up the legend, titles, etc. for the plots
    plt.legend(
        (a_vs_lambda_plot, p_vs_lambda_plot,
         r_vs_lambda_plot, f1_vs_lambda_plot),
        ('accuracy', 'precision', 'recall', 'F-1'),
        loc='best'
    )

    plt.title('Testing descriptions')
    plt.xlabel('regularization parameter')
    plt.ylabel('Metric')
    plt.savefig('hw4pr2a_description.png', format='png')
    plt.close()

    print('==> Plotting completed.')

    # Find the lambda that maximizes accuracy
    reg_opt = reg_list[np.argmax(a_list)]

    print('-- Best test accuracy is {:2.4f}'.format(max(a_list)))

    return reg_opt


###########################################
#           Main Driver Function          #
###########################################

if __name__ == '__main__':

    # =============STEP 0: LOADING DATA=================
    # NOTE: The data is loaded using the code in p2_data.py. Please make sure
    #       you read the code in that file and understand how it works.

    # data frame
    df_train = data.df_train
    df_test = data.df_test

    # training data
    X_train = data.X_train
    y_train = data.y_train

    # test data
    X_test = data.X_test
    y_test = data.y_test

    # =============STEP 1: Logistic regression=================
    print('\n\n==> Step 1: Running logistic regression...')

    # splitting data for logistic regression
    # NOTE: for logistic regression, we only want images with label 0 or 1.
    df_train_logreg = df_train[df_train.label <= 1]
    df_test_logreg = df_test[df_test.label <= 1]

    # training data for logistic regression
    X_train_logreg = np.array(
        df_train_logreg[
            [col for col in df_train_logreg.columns if col != 'label']
        ]
    ) / 256.

    y_train_logreg = np.array(df_train_logreg[['label']])

    # testing data for logistic regression
    X_test_logreg = np.array(
        df_test_logreg[
            [col for col in df_test_logreg.columns if col != 'label']
        ]
    ) / 256.

    y_test_logreg = np.array(df_test_logreg[['label']])

    # stacking a column of 1's to both training and testing data
    X_train_logreg = np.hstack(
        (np.ones_like(y_train_logreg), X_train_logreg)
    )

    X_test_logreg = np.hstack(
        (np.ones_like(y_test_logreg), X_test_logreg)
    )

    # ========STEP 1a: Gradient descent=========
    print('\n==> Step 1a: Running gradient descent...')

    W_gd, nll_list_gd = grad_descent(
        X_train_logreg,
        y_train_logreg,
        reg=1e-6
    )

    # ========STEP 1b: Newton's method==========
    print("\n==> Step 1b: Running Newton's method...")

    W_newton, nll_list_newton = newton_method(
        X_train_logreg,
        y_train_logreg,
        reg=1e-6
    )

    # =============STEP 2: Generate convergence plot=================
    print('\n==> Step 2: Generate Convergence Plot...')
    print('==> Plotting convergence plot...')

    # set up the style for the plot
    plt.style.use('ggplot')

    # plot gradient descent and Newton's method convergence plot
    nll_gd_plot, = plt.plot(
        range(len(nll_list_gd)),
        nll_list_gd
    )

    plt.setp(nll_gd_plot, color='red')

    nll_newton_plot, = plt.plot(
        range(len(nll_list_newton)),
        nll_list_newton
    )

    plt.setp(nll_newton_plot, color='green')

    # add legend, titles, etc. for the plots
    plt.legend(
        (nll_gd_plot, nll_newton_plot),
        ('Gradient descent', "Newton's method"),
        loc='best'
    )

    plt.title('Convergence Plot on Binary MNIST Classification')
    plt.xlabel('Iteration')
    plt.ylabel('NLL')
    plt.savefig('hw4pr2a_convergence.png', format='png')
    plt.close()

    print('==> Plotting completed.')

    # =============STEP 3: Generate accuracy/precision plot=================
    print(
        '\nStep 3: ==> Generating plots for accuracy, '
        'precision, recall, and F-1 score...'
    )

    # Plot the graph and obtain the optimal regularization parameter
    reg_opt = plot_description(
        X_train_logreg,
        y_train_logreg,
        X_test_logreg,
        y_test_logreg
    )

    print(
        '\n==> Optimal regularization parameter is '
        '{:4.4f}'.format(reg_opt)
    )

"""
Start file for hw4pr2 part (b) of Big Data Summer 2017

The file is seperated into two parts:
    1) the helper functions
    2) the main driver.

The helper functions are all functions necessary to finish the problem.
The main driver will use the helper functions you finished to report and print
out the results you need for the problem.

First, please COMMENT OUT any steps other than step 0 in main driver before
you finish the corresponding functions for that step. Otherwise, you won't be
able to run the program because of errors.

After finishing the helper functions for each step, you can uncomment
the code in main driver to check the result.

Note:
1. Please read the instructions and hints carefully, and use the name of the
variables we provided, otherwise, the function may not work.

2. Remember to comment out the TODO comment after you finish each part.
"""


#########################################
#            Helper Functions           #
#########################################

import p2_data as data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
import time


def NLL(X, y, W, reg=0.0):
    """ This function takes in four arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) y, the label of the data with dimension m x k
            3) W, a weight matrix
            4) reg, the parameter for regularization

        This function calculates and returns negative log likelihood for
        softmax regression.
    """

    # Calculate scores
    scores = X @ W

    # Subtract maximum for numerical stability
    scores = scores - np.max(scores, axis=1, keepdims=True)

    # Calculate softmax probabilities
    exp_scores = np.exp(scores)

    probabilities = exp_scores / np.sum(
        exp_scores,
        axis=1,
        keepdims=True
    )

    # Prevent taking log(0)
    probabilities = np.clip(
        probabilities,
        1e-12,
        1.0
    )

    # Find negative log likelihood for softmax regression
    NLL = -(y * np.log(probabilities)).sum()
    NLL += reg * (np.linalg.norm(W) ** 2)

    return NLL


def grad_softmax(X, y, W, reg=0.0):
    """ This function takes in four arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) y, the label of the data with dimension m x k
            3) W, a weight matrix
            4) reg, the parameter for regularization

        This function calculates and returns the gradient of W for softmax
        regression.

        NOTE: Please use the variable given for the gradient, grad.
    """

    # Calculate scores
    scores = X @ W

    # Subtract maximum for numerical stability
    scores = scores - np.max(scores, axis=1, keepdims=True)

    # Calculate softmax probabilities
    exp_scores = np.exp(scores)

    probabilities = exp_scores / np.sum(
        exp_scores,
        axis=1,
        keepdims=True
    )

    # Find the gradient of softmax regression with respect to W
    grad = X.T @ (probabilities - y) + 2 * reg * W

    return grad


def predict(X, W):
    """ This function takes in two arguments:
            1) X, the data matrix with dimension m x (n + 1)
            2) W, a weight matrix

        This function returns the predicted labels y_pred with
        dimension m x 1.
    """

    # Calculate scores
    scores = X @ W

    # Subtract maximum for numerical stability
    scores = scores - np.max(scores, axis=1, keepdims=True)

    # Calculate softmax probabilities
    exp_scores = np.exp(scores)

    probabilities = exp_scores / np.sum(
        exp_scores,
        axis=1,
        keepdims=True
    )

    # Obtain predicted label
    y_pred = np.argmax(
        probabilities,
        axis=1
    ).reshape(-1, 1)

    return y_pred


def get_accuracy(y_pred, y):
    """ This function takes in two arguments:
            1) y_pred, the predicted label of data with dimension m x 1
            2) y, the true label of data with dimension m x 1

        This function calculates and returns the accuracy of the prediction.

        NOTE: You DO NOT need to change this function.
    """

    diff = (y_pred == y).astype(int)
    accu = 1. * diff.sum() / len(y)

    return accu


def grad_descent(X, y, reg=0.0, lr=1e-5, eps=1e-6,
                 max_iter=500, print_freq=20):
    """ This function takes in seven arguments:
            1) X, the data with dimension m x (n + 1)
            2) y, the one-hot encoded labels
            3) reg, the parameter for regularization
            4) lr, the learning rate
            5) eps, the threshold of the norm for the gradients
            6) max_iter, the maximum number of iterations
            7) print_freq, the frequency of printing the report

        This function returns W, the optimal weight by gradient descent,
        and nll_list, the corresponding learning objectives.
    """

    # get the shape of the data, and initialize nll_list
    m, n = X.shape
    k = y.shape[1]
    nll_list = []

    # initialize the weight and its gradient
    W = np.zeros((n, k))
    W_grad = np.ones((n, k))

    print('\n==> Running gradient descent...')

    # Start iteration for gradient descent
    iter_num = 0
    t_start = time.time()

    # Run gradient descent algorithm
    while iter_num < max_iter and np.linalg.norm(W_grad) > eps:

        # Calculate negative log likelihood
        nll = NLL(X, y, W, reg)

        # Test for NaN
        if np.isnan(nll):
            print('NaN encountered. Stopping gradient descent.')
            break

        # Append NLL
        nll_list.append(nll)

        # Calculate gradient
        W_grad = grad_softmax(X, y, W, reg)

        # Update W
        W = W - lr * W_grad

        # Print statements for debugging
        if (iter_num + 1) % print_freq == 0:
            print('-- Iteration {} - negative log likelihood {: 4.4f}'.format(
                iter_num + 1, nll))

        # Goes to the next iteration
        iter_num += 1

    # benchmark
    t_end = time.time()

    print(
        '-- Time elapsed for running gradient descent: '
        '{t:2.2f} seconds'.format(t=t_end - t_start)
    )

    return W, nll_list


def accuracy_vs_lambda(
        X_train,
        y_train_OH,
        X_test,
        y_test,
        lambda_list):
    """ This function takes in five arguments:
            1) X_train, the training data with dimension m x (n + 1)
            2) y_train_OH, the one-hot encoded training labels
            3) X_test, the testing data with dimension m x (n + 1)
            4) y_test, the testing labels
            5) lambda_list, a list of different regularization parameters

        This function generates a plot of accuracy of prediction vs lambda and
        returns the regularization parameter that maximizes the accuracy,
        reg_opt.
    """

    # initialize the list of accuracy
    accu_list = []

    # Find corresponding accuracy values for each parameter
    for reg in lambda_list:

        # Run gradient descent
        W_opt, nll_list = grad_descent(
            X_train,
            y_train_OH,
            reg=reg
        )

        # Predict testing labels
        y_pred = predict(
            X_test,
            W_opt
        )

        # Calculate accuracy
        accuracy = get_accuracy(
            y_pred,
            y_test
        )

        # Append accuracy
        accu_list.append(accuracy)

        print(
            '-- Accuracy is {:2.4f} for lambda = {:2.2f}'.format(
                accuracy,
                reg
            )
        )

    # Plot accuracy vs lambda
    print('==> Printing accuracy vs lambda...')

    plt.style.use('ggplot')

    plt.plot(
        lambda_list,
        accu_list
    )

    plt.title('Accuracy versus Lambda in Softmax Regression')
    plt.xlabel('Lambda')
    plt.ylabel('Accuracy')

    plt.savefig(
        'hw4pr2b_lva.png',
        format='png'
    )

    plt.close()

    print('==> Plotting completed.')

    # Find the optimal lambda that maximizes the accuracy
    reg_opt = lambda_list[np.argmax(accu_list)]

    print(
        '-- Best test accuracy is {:2.4f}'.format(
            max(accu_list)
        )
    )

    return reg_opt


###########################################
#           Main Driver Function          #
###########################################

if __name__ == '__main__':

    # =============STEP 0: LOADING DATA=================
    # NOTE: The data is loaded using the code in p2_data.py. Please make sure
    #       you read the code in that file and understand how it works.

    df_train = data.df_train
    df_test = data.df_test

    X_train = data.X_train
    y_train = data.y_train

    X_test = data.X_test
    y_test = data.y_test

    # stacking an array of ones
    X_train = np.hstack(
        (np.ones_like(y_train), X_train)
    )

    X_test = np.hstack(
        (np.ones_like(y_test), X_test)
    )

    # one hot encoder
    enc = OneHotEncoder()

    y_train_OH = enc.fit_transform(
        y_train.copy()
    ).astype(int).toarray()

    y_test_OH = enc.transform(
        y_test.copy()
    ).astype(int).toarray()

    # =============STEP 1: Accuracy versus lambda=================
    print(
        '\n\n==> Step 1: Finding optimal regularization parameter...'
    )

    lambda_list = [
        0.01,
        0.1,
        0.5,
        1.0,
        10.0,
        50.0,
        100.0,
        200.0,
        500.0,
        1000.0
    ]

    reg_opt = accuracy_vs_lambda(
        X_train,
        y_train_OH,
        X_test,
        y_test,
        lambda_list
    )

    print(
        '\n-- Optimal regularization parameter is '
        '{:2.2f}'.format(reg_opt)
    )

    # =============STEP 2: Convergence plot=================
    # run gradient descent to get the nll_list
    W_gd, nll_list_gd = grad_descent(
        X_train,
        y_train_OH,
        reg=reg_opt,
        max_iter=1500,
        lr=2e-5,
        print_freq=100
    )

    # Report final test accuracy
    y_pred = predict(
        X_test,
        W_gd
    )

    final_accuracy = get_accuracy(
        y_pred,
        y_test
    )

    print(
        '\n==> Test accuracy for optimal lambda: '
        '{:2.4f}'.format(final_accuracy)
    )

    print(
        '\n==> Step 2: Plotting convergence plot...'
    )

    # set up style for the plot
    plt.style.use('ggplot')

    # generate the convergence plot
    nll_gd_plot, = plt.plot(
        range(len(nll_list_gd)),
        nll_list_gd
    )

    plt.setp(
        nll_gd_plot,
        color='red'
    )

    # add title, labels, etc and save the figure
    plt.title(
        'Convergence Plot on Softmax Regression '
        'with $\\lambda = {:2.2f}$'.format(reg_opt)
    )

    plt.xlabel('Iteration')
    plt.ylabel('NLL')

    plt.savefig(
        'hw4pr2b_convergence.png',
        format='png'
    )

    plt.close()

    print('==> Plotting completed.')

    """
For the L2-regularized softmax regression model, the maximum test accuracy
was approximately 91.93%. The smallest tested regularization parameters
\(\lambda=0.01,0.1,0.5,\) and \(1.0\) produced the same displayed maximum
test accuracy. The implementation selected \(\lambda=0.01\) as the optimal
value because it was the first value attaining the maximum. As \(\lambda\)
increased further, test accuracy decreased, indicating that excessive
regularization reduced model performance. The convergence plot for
\(\lambda=0.01\) shows that the negative log-likelihood decreases substantially
over the 1500 gradient-descent iterations.
    """